config/routes.rb
Rails.application.routes.draw do
  resources :reservations

  resources :users, only: [:show, :edit, :update]
  get  'users/:token/token/', controller: :users, action: :token # /users/E3YwkxZfBTjAHC9vPKGHtw/token

  get  'confirmations/new'

  get  'sessions/new'
  post 'sessions/create'

   root 'sessions#new'

end

app/models/reservation.rb
class Reservation
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include DynamicAttributeSupport

  field :user_id,                type: :relation
  field :preferred_housing_date, type: DateTime
  field :additional_questions,   type: String
  field :rating,                 type: Integer

  belongs_to :user

  delegate :email, :telephone, :first_name, :last_name, :full_name, to: :user

  # Revue note:
  # Having no info about how the rating should be related, I opted for the simplest: the reservation
  # so I just added a field to the reservation record

  # dynamic fields - todo if many or variable, move to DB and probably embed in reservation
  def self.amenities
    @amenities ||= [:pool, :rec_room, :movie, :theater, :on_site_doctor, :time_machine ]
  end

  def amenities
    self.class.amenities
  end

  def add_dynamic_fields(dyna_fields, type=String)
    # add the dynamic fields in the singleton
    (class << self; self; end).class_eval do
      [dyna_fields].flatten.each { |df| field df, type: type }
    end
  end

end

app/models/user.rb
class User
  include Mongoid::Document

  field :first_name, type: :string
  field :last_name, type: String
  field :telephone, type: String
  field :email,  type: String
  field :active, type: Mongoid::Boolean, default: false
  field :token,  type: String

  has_many :reservations, dependent: :delete

  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ }
  validates :telephone,
            presence: true,
            format: { with: /\A\d{3}[ -:]?\d{3}[ -:]?\d{4}\Z/ },
            on: :update

  class << self

    def active
      where(active: true)
    end

    def inactive
      where(active: false)
    end

  end

  def active?
    true == active
  end

  def inactive?
    false == active
  end

  def activate
    if inactive?
      self.update_attribute :active, true
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
    def current_user
      return unless session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end

    def check_current_user
      unless current_user
        redirect_to "/" and return
      end
      true
    end

end

app/controllers/reservations_controller.rb
class ReservationsController < InheritedResources::Base
  respond_to :html

  def new
    @reservation = Reservation.new
    @reservation.add_dynamic_fields @reservation.amenities, Boolean
  end

  def create
    @reservation = current_user.reservations.new(reservation_params)
    if @reservation.valid? && check_date(@reservation, :preferred_housing_date, reservation_params)
      @reservation.save!
      send_confirmation_emails @reservation, current_user, request
      redirect_to @reservation
    else
      render new_reservation_path and return
    end
  end

  private
  def reservation_params
    params.require(:reservation).permit([:preferred_housing_date, :additional_questions, :rating].concat(Reservation.amenities))
  end

  def send_confirmation_emails(reservation, current_user, request)
    UserMailer.confirmation_reservation(reservation, current_user, request.host_with_port).deliver
    OfficeMailer.desk_resa_request(reservation, current_user, request.ip).deliver
  end

  def check_date(model, date_field, model_params)
    true
    begin
    Date.strptime(model_params[date_field], '%m/%d/%Y')
    rescue ArgumentError
      model.errors.add date_field, "Error date must be in the format MM/DD/YYYY"
      false
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def create
    @user = User.new(email: params["email"], token: SecureRandom.urlsafe_base64)
    @host = request.host_with_port
    respond_to do |format|
      format.html do
        if @user.save
          UserMailer.confirmation_request(@user, @host).deliver
        else
          redirect_to "/", notice: "Email #{params[:email]} already taken of format error"
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  actions :show, :update
  respond_to :html


  def token
    @user = User.where(token: params[:token]).first
    if @user
      session[:user_id] = @user.id.to_s
      if @user.inactive?
        @user.activate
      elsif @user.reservations.any?
        redirect_to @user.reservations.first
      else
        # nothing to do just render user_profile
      end
    else
      redirect_to  "/", alert: "User not found"
    end
  end

  def update
    @user = current_user
    @user.attributes = user_params
    if @user.valid?
      @user.save!
      redirect_to new_reservation_path
    else
      render :token
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :telephone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper

  def full_name
    @reservation.full_name
  end

  def email
    @reservation.email
  end

  def telephone
    @reservation.telephone
  end

  def preferred_housing_date
    @reservation.preferred_housing_date
  end

  def additional_questions
    @reservation.additional_questions
  end

  def rating
    @reservation.rating
  end

  def amenities
    ret = ""
    Reservation.amenities.each do |amenity|
      if ['1', true].include? @reservation.send(amenity)
        ret << amenity.to_s.humanize << "\n<br>"
      end
    end
    ret.html_safe
  end

  def rating_box
    if @reservation.rating
      render partial: "rating_results"
    else
      render partial: "rating_form"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timeshare</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/reservations/_form.html.slim
= form_for @reservation do |f|
  - if @reservation.errors.any?
    #error_explanation
      h2 = "#{pluralize(@reservation.errors.count, "error")} prohibited this reservation from being saved:"
      ul
        - @reservation.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :preferred_housing_date
    = f.text_field :preferred_housing_date
  .field
    = f.label :additional_questions
    = f.text_field :additional_questions

  'Amenities
  - Reservation.amenities.each do |amenity|
    .field
      = f.check_box amenity
      = f.label amenity

  .actions = f.submit 'Save'

app/views/reservations/_rating_form.html.slim
strong> Please rate your reservation experience:
= form_for @reservation do |f|
  .field
    = f.radio_button( :rating, "1")
    = f.label :rating, '1 ' ,value: "1"
    = f.radio_button( :rating, "2")
    = f.label :rating, '2 ' ,value: "2"
    = f.radio_button( :rating, "3")
    = f.label :rating, '3 ' ,value: "3"
    = f.radio_button( :rating, "4")
    = f.label :rating, '4 ' ,value: "4"
    = f.radio_button( :rating, "5")
    = f.label :rating, '5 ' ,value: "5"
  .action = f.submit "Rate your experience"

app/views/reservations/_rating_results.html.slim
strong> Your rating:
= rating

app/views/reservations/new.html.slim
h1 New reservation

== render 'form'

= link_to 'Back', reservations_path

app/views/reservations/show.html.slim
p#notice = notice

H2 Your reservation request has been successful

p Here you reservation details:

p
  strong> Name:
  = full_name
p
  strong> Email:
  = email
p
  strong> Telephone:
  = telephone
p
  strong> Email:
  = email
p
  strong> Preferred housing date:
  = preferred_housing_date
p
  strong> Additional questions:
  = additional_questions
p
  strong Amenities:
  br
  = amenities
P
  = rating_box

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :telephone
    = f.text_field :telephone
  .actions = f.submit 'Save'

app/views/users/show.html.slim
p#notice = notice

p
  strong First name:
  = @user.first_name
p
  strong Last name:
  = @user.last_name
p
  strong Telephone:
  = @user.telephone

/= link_to 'Edit', edit_user_path(@user)
/'|
/= link_to 'Back', users_path

app/views/users/token.html.slim
h1 Please complete your information

== render 'form'